# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-13 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='home.Teacher'),
        ),
    ]
